export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const CREATE_CONTACT_SUCCESS = "CREATE_CONTACT_SUCCESS";
export const CREATE_CONTACT_FAIL = "CREATE_CONTACT_FAIL";
export const GET_ALL_CONTACTS_SUCCESS = "GET_ALL_CONTACTS_SUCCESS";
export const GET_ALL_CONTACTS_FAIL = "GET_ALL_CONTACTS_FAIL";

export const CREATE_SHOW_SUCCESS = "CREATE_SHOW_SUCCESS";
export const CREATE_SHOW_FAIL = "CREATE_SHOW_FAIL";
export const GET_ALL_SHOWS_SUCCESS = "GET_ALL_SHOWS_SUCCESS";
export const GET_ALL_SHOWS_FAIL = "GET_ALL_SHOWS_FAIL";
export const GET_SHOW_SUCCESS = "GET_SHOW_SUCCESS";
export const GET_SHOW_FAIL = "GET_SHOW_FAIL";
export const UPDATE_SHOW_REQUEST = "UPDATE_SHOW_REQUES";
export const UPDATE_SHOW_SUCCESS = "UPDATE_SHOW_SUCCESS";
export const UPDATE_SHOW_FAILURE = "UPDATE_SHOW_FAILURE";
export const DELETE_SHOW_REQUEST = "DELETE_SHOW_REQUEST";
export const DELETE_SHOW_SUCCESS = "DELETE_SHOW_SUCCESS";
export const DELETE_SHOW_FAILURE = "DELETE_SHOW_FAILURE";
